# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Mutation tests

on:
  schedule:
    - cron: '0 13 * * 5'

jobs:
  applications:
    name: Mutation Test ${{ matrix.java-version }}
    if: github.repository == 'eclipse/eclipse-collections'
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [17]

    runs-on: ${{ matrix.os }}

    env:
      JAVA_VERSION: ${{ matrix.java-version }}

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Set JDK ${{ matrix.java-version }}
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
      - name: Enable Maven Cache
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn --non-recursive wrapper:wrapper -Dmaven=3.9.6
      - run: ./mvnw --color=always install -DskipTests=true
        env:
          MAVEN_OPTS: '-Xmx1g'
      - name: Mutation Test
        run: mvn eu.stamp-project:pitmp-maven-plugin:run -DwithHistory -DtimeoutConstant=8000
        env:
          MAVEN_OPTS: '-Xmx1g'
      - name: Archive pitest reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: pit-reports
          path: unit-tests/target/pit-reports
